/**
 * Datos ficticios del prototipo Forja Training (Powerlifting).
 * Solo demo de validación — no es Forja productivo.
 */

import { finanzasInicial, WORKSPACE_DEMO, COACH_DEMO } from './finanzas/seed.js';

/** Clave localStorage exclusiva de forja-demo (no usar claves de Forkza Gestión). */
export const STORAGE_KEY = 'forja-demo-v1';

/** Versión del documento de estado (v2 agrega Finanzas). */
export const STATE_VERSION = 2;

export const COACH = {
  id: COACH_DEMO.id,
  nombre: COACH_DEMO.nombre,
  modalidad: COACH_DEMO.modalidad,
  rol: COACH_DEMO.rol,
  workspace: WORKSPACE_DEMO.nombre,
  workspaceId: WORKSPACE_DEMO.id,
};

export const GRUPOS = [
  { id: 'grp-inicial', nombre: 'Powerlifting Inicial' },
  { id: 'grp-comp', nombre: 'Powerlifting Competencia' },
];

export const ALUMNOS_SEED = [
  {
    id: 'alu-01',
    nombre: 'Camila Torres',
    grupoId: 'grp-inicial',
    modalidades: ['Powerlifting'],
    edad: 28,
    pesoCorporal: 63,
    oneRm: { squat: 95, bench: 55, deadlift: 120 },
    estadoHoy: 'pendiente',
    adherencia: 86,
  },
  {
    id: 'alu-02',
    nombre: 'Diego Fuentes',
    grupoId: 'grp-inicial',
    modalidades: ['Powerlifting'],
    edad: 32,
    pesoCorporal: 82,
    oneRm: { squat: 140, bench: 100, deadlift: 180 },
    estadoHoy: 'completado',
    adherencia: 92,
  },
  {
    id: 'alu-03',
    nombre: 'Valentina Ruiz',
    grupoId: 'grp-inicial',
    modalidades: ['Powerlifting', 'Fuerza general'],
    edad: 24,
    pesoCorporal: 58,
    oneRm: { squat: 80, bench: 45, deadlift: 100 },
    estadoHoy: 'pendiente',
    adherencia: 78,
  },
  {
    id: 'alu-04',
    nombre: 'Andrés Morales',
    grupoId: 'grp-comp',
    modalidades: ['Powerlifting'],
    edad: 29,
    pesoCorporal: 93,
    oneRm: { squat: 210, bench: 145, deadlift: 250 },
    estadoHoy: 'completado',
    adherencia: 95,
  },
  {
    id: 'alu-05',
    nombre: 'Francisca Negrete',
    grupoId: 'grp-comp',
    modalidades: ['Powerlifting'],
    edad: 27,
    pesoCorporal: 67,
    oneRm: { squat: 130, bench: 75, deadlift: 155 },
    estadoHoy: 'alerta',
    adherencia: 71,
  },
  {
    id: 'alu-06',
    nombre: 'Tomás Herrera',
    grupoId: 'grp-comp',
    modalidades: ['Powerlifting'],
    edad: 35,
    pesoCorporal: 105,
    oneRm: { squat: 240, bench: 160, deadlift: 280 },
    estadoHoy: 'pendiente',
    adherencia: 88,
  },
  {
    id: 'alu-07',
    nombre: 'Javiera Soto',
    grupoId: 'grp-inicial',
    modalidades: ['Powerlifting'],
    edad: 22,
    pesoCorporal: 54,
    oneRm: { squat: 70, bench: 40, deadlift: 90 },
    estadoHoy: 'completado',
    adherencia: 90,
  },
];

export const EJERCICIOS_SISTEMA = [
  {
    id: 'ex-squat',
    nombre: 'Competition Squat',
    tipo: 'principal',
    modalidad: 'Powerlifting',
    patron: 'Sentadilla',
    levantamiento: 'Sentadilla',
    variante: null,
    grupoMuscular: 'Cuádriceps / glúteos',
    equipamiento: 'Barra olímpica + rack',
    nivel: 'Intermedio',
    objetivo: 'Fuerza máxima',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: 'Referencia IPF: profundidad y control de barra.',
  },
  {
    id: 'ex-bench',
    nombre: 'Competition Bench Press',
    tipo: 'principal',
    modalidad: 'Powerlifting',
    patron: 'Empuje horizontal',
    levantamiento: 'Press banca',
    variante: null,
    grupoMuscular: 'Pectoral / tríceps',
    equipamiento: 'Banca + barra',
    nivel: 'Intermedio',
    objetivo: 'Fuerza máxima',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: 'Referencia IPF: pausa en pecho y bloqueo.',
  },
  {
    id: 'ex-dl',
    nombre: 'Competition Deadlift',
    tipo: 'principal',
    modalidad: 'Powerlifting',
    patron: 'Bisagra de cadera',
    levantamiento: 'Peso muerto',
    variante: null,
    grupoMuscular: 'Cadena posterior',
    equipamiento: 'Barra olímpica',
    nivel: 'Intermedio',
    objetivo: 'Fuerza máxima',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: 'Referencia IPF: bloqueo de rodillas y hombros.',
  },
  {
    id: 'ex-pause-sq',
    nombre: 'Pause Squat',
    tipo: 'variante',
    modalidad: 'Powerlifting',
    patron: 'Sentadilla',
    levantamiento: 'Sentadilla',
    variante: 'Pausa',
    grupoMuscular: 'Cuádriceps',
    equipamiento: 'Barra + rack',
    nivel: 'Intermedio',
    objetivo: 'Estabilidad en hoyo',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: 'Pausa 2 s en paralelo; criterio del coach.',
  },
  {
    id: 'ex-tempo-sq',
    nombre: 'Tempo Squat',
    tipo: 'variante',
    modalidad: 'Powerlifting',
    patron: 'Sentadilla',
    levantamiento: 'Sentadilla',
    variante: 'Tempo',
    grupoMuscular: 'Cuádriceps',
    equipamiento: 'Barra + rack',
    nivel: 'Intermedio',
    objetivo: 'Control excéntrico',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: 'Tempo 3-1-1; programación del coach.',
  },
  {
    id: 'ex-cg-bench',
    nombre: 'Close Grip Bench Press',
    tipo: 'variante',
    modalidad: 'Powerlifting',
    patron: 'Empuje horizontal',
    levantamiento: 'Press banca',
    variante: 'Agarre cerrado',
    grupoMuscular: 'Tríceps',
    equipamiento: 'Banca + barra',
    nivel: 'Intermedio',
    objetivo: 'Lockout banca',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: 'Agarre más estrecho; no es estándar IPF.',
  },
  {
    id: 'ex-pause-bench',
    nombre: 'Paused Bench Press',
    tipo: 'variante',
    modalidad: 'Powerlifting',
    patron: 'Empuje horizontal',
    levantamiento: 'Press banca',
    variante: 'Pausa',
    grupoMuscular: 'Pectoral',
    equipamiento: 'Banca + barra',
    nivel: 'Intermedio',
    objetivo: 'Fuerza desde pecho',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: 'Pausa controlada; criterio del coach.',
  },
  {
    id: 'ex-rdl',
    nombre: 'Romanian Deadlift',
    tipo: 'variante',
    modalidad: 'Powerlifting',
    patron: 'Bisagra de cadera',
    levantamiento: 'Peso muerto',
    variante: 'Rumano',
    grupoMuscular: 'Isquios / lumbar',
    equipamiento: 'Barra',
    nivel: 'Intermedio',
    objetivo: 'Cadena posterior',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: 'Rodillas fijas; programación del coach.',
  },
  {
    id: 'ex-def-dl',
    nombre: 'Deficit Deadlift',
    tipo: 'variante',
    modalidad: 'Powerlifting',
    patron: 'Bisagra de cadera',
    levantamiento: 'Peso muerto',
    variante: 'Déficit',
    grupoMuscular: 'Cadena posterior',
    equipamiento: 'Barra + plataforma',
    nivel: 'Avanzado',
    objetivo: 'Fuerza desde piso',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: 'Déficit 2–4 cm; criterio del coach.',
  },
  {
    id: 'ex-row',
    nombre: 'Remo con barra',
    tipo: 'accesorio',
    modalidad: 'Powerlifting',
    patron: 'Tracción horizontal',
    levantamiento: null,
    variante: null,
    grupoMuscular: 'Dorsal',
    equipamiento: 'Barra',
    nivel: 'Básico',
    objetivo: 'Equilibrio de empuje',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: '',
  },
  {
    id: 'ex-lat',
    nombre: 'Jalón al pecho',
    tipo: 'accesorio',
    modalidad: 'Powerlifting',
    patron: 'Tracción vertical',
    levantamiento: null,
    variante: null,
    grupoMuscular: 'Dorsal',
    equipamiento: 'Polea',
    nivel: 'Básico',
    objetivo: 'Espalda alta',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: '',
  },
  {
    id: 'ex-legpress',
    nombre: 'Prensa de piernas',
    tipo: 'accesorio',
    modalidad: 'Powerlifting',
    patron: 'Empuje de piernas',
    levantamiento: null,
    variante: null,
    grupoMuscular: 'Cuádriceps',
    equipamiento: 'Máquina',
    nivel: 'Básico',
    objetivo: 'Volumen de piernas',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: '',
  },
  {
    id: 'ex-legext',
    nombre: 'Extensión de piernas',
    tipo: 'accesorio',
    modalidad: 'Powerlifting',
    patron: 'Aislamiento',
    levantamiento: null,
    variante: null,
    grupoMuscular: 'Cuádriceps',
    equipamiento: 'Máquina',
    nivel: 'Básico',
    objetivo: 'Hipertrofia local',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: '',
  },
  {
    id: 'ex-legcurl',
    nombre: 'Curl femoral',
    tipo: 'accesorio',
    modalidad: 'Powerlifting',
    patron: 'Aislamiento',
    levantamiento: null,
    variante: null,
    grupoMuscular: 'Isquiotibiales',
    equipamiento: 'Máquina',
    nivel: 'Básico',
    objetivo: 'Cadena posterior',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: '',
  },
  {
    id: 'ex-tricep',
    nombre: 'Extensión de tríceps',
    tipo: 'accesorio',
    modalidad: 'Powerlifting',
    patron: 'Aislamiento',
    levantamiento: null,
    variante: null,
    grupoMuscular: 'Tríceps',
    equipamiento: 'Polea',
    nivel: 'Básico',
    objetivo: 'Lockout banca',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: '',
  },
  {
    id: 'ex-abs',
    nombre: 'Trabajo abdominal',
    tipo: 'accesorio',
    modalidad: 'Powerlifting',
    patron: 'Estabilidad',
    levantamiento: null,
    variante: null,
    grupoMuscular: 'Core',
    equipamiento: 'Peso corporal / cable',
    nivel: 'Básico',
    objetivo: 'Estabilidad de torso',
    fuente: 'sistema',
    notasCoach: '',
    refTecnica: '',
  },
];

/** Periodización de ejemplo — criterio del coach, no prescrita por IPF. */
export const MACRO_SEED = {
  id: 'macro-01',
  nombre: 'Ciclo Competencia Regional 2026',
  objetivo: 'Preparar total competitivo con peaking controlado',
  fechaInicio: '2026-07-01',
  fechaFin: '2026-11-15',
  competencia: 'Test / competencia regional (noviembre)',
  notaIpf:
    'IPF se usa solo como referencia técnica de sentadilla, banca y peso muerto. La periodización es criterio del coach.',
  mesociclos: [
    {
      id: 'meso-1',
      nombre: 'Base / acumulación',
      semanas: 4,
      objetivo: 'Volumen y técnica',
    },
    {
      id: 'meso-2',
      nombre: 'Desarrollo de fuerza',
      semanas: 4,
      objetivo: 'Fuerza submáxima',
    },
    {
      id: 'meso-3',
      nombre: 'Intensificación',
      semanas: 3,
      objetivo: 'Intensidad alta',
    },
    {
      id: 'meso-4',
      nombre: 'Peaking',
      semanas: 2,
      objetivo: 'Exposición a cargas altas',
    },
    {
      id: 'meso-5',
      nombre: 'Taper y test',
      semanas: 1,
      objetivo: 'Descarga y evaluación',
    },
  ],
};

export const MICRO_SEED = {
  mesoId: 'meso-2',
  semana: 2,
  objetivoSemanal: 'Sentadilla y banca con volumen moderado',
  volumen: 'Medio-alto',
  intensidad: '70–82% 1RM',
  dias: [
    { id: 'dia-lun', nombre: 'Lunes', foco: 'Sentadilla + banca' },
    { id: 'dia-mie', nombre: 'Miércoles', foco: 'Peso muerto + accesorios' },
    { id: 'dia-vie', nombre: 'Viernes', foco: 'Variantes + técnica' },
  ],
};

export function sesionSeed() {
  return {
    id: 'ses-lunes',
    titulo: 'Día de sentadilla y banca',
    diaId: 'dia-lun',
    alumnoId: 'alu-04',
    ejercicios: [
      {
        id: 'item-1',
        ejercicioId: 'ex-squat',
        variante: 'Competition',
        series: 4,
        repeticiones: 3,
        peso: 168,
        pct1rm: 80,
        rpeObjetivo: 7.5,
        rir: 2,
        descanso: '180 s',
        notas: 'Profundidad completa; brace firme.',
        videoPlaceholder: true,
        orden: 1,
      },
      {
        id: 'item-2',
        ejercicioId: 'ex-pause-sq',
        variante: 'Pausa 2 s',
        series: 3,
        repeticiones: 4,
        peso: 147,
        pct1rm: 70,
        rpeObjetivo: 7,
        rir: 3,
        descanso: '150 s',
        notas: 'Pausa controlada en paralelo.',
        videoPlaceholder: true,
        orden: 2,
      },
      {
        id: 'item-3',
        ejercicioId: 'ex-bench',
        variante: 'Competition',
        series: 4,
        repeticiones: 3,
        peso: 116,
        pct1rm: 80,
        rpeObjetivo: 7.5,
        rir: 2,
        descanso: '180 s',
        notas: 'Pausa competitiva; pies firmes.',
        videoPlaceholder: true,
        orden: 3,
      },
      {
        id: 'item-4',
        ejercicioId: 'ex-cg-bench',
        variante: 'Agarre cerrado',
        series: 3,
        repeticiones: 6,
        peso: 95,
        pct1rm: 65,
        rpeObjetivo: 7,
        rir: 3,
        descanso: '120 s',
        notas: 'Codos cerca del torso.',
        videoPlaceholder: true,
        orden: 4,
      },
      {
        id: 'item-5',
        ejercicioId: 'ex-row',
        variante: '—',
        series: 3,
        repeticiones: 8,
        peso: 70,
        pct1rm: null,
        rpeObjetivo: 7,
        rir: 3,
        descanso: '90 s',
        notas: 'Remo controlado.',
        videoPlaceholder: false,
        orden: 5,
      },
      {
        id: 'item-6',
        ejercicioId: 'ex-tricep',
        variante: '—',
        series: 3,
        repeticiones: 12,
        peso: 25,
        pct1rm: null,
        rpeObjetivo: 7,
        rir: 3,
        descanso: '60 s',
        notas: 'Sin balanceo.',
        videoPlaceholder: false,
        orden: 6,
      },
      {
        id: 'item-7',
        ejercicioId: 'ex-abs',
        variante: '—',
        series: 3,
        repeticiones: 15,
        peso: 0,
        pct1rm: null,
        rpeObjetivo: 6,
        rir: 4,
        descanso: '45 s',
        notas: 'Core anti-extensión.',
        videoPlaceholder: false,
        orden: 7,
      },
    ],
  };
}

export const PANEL_SEED = {
  sesionesHoy: [
    { alumnoId: 'alu-04', hora: '09:00', sesion: 'Sentadilla + banca' },
    { alumnoId: 'alu-02', hora: '11:30', sesion: 'Variantes técnica' },
    { alumnoId: 'alu-06', hora: '18:00', sesion: 'Sentadilla + banca' },
    { alumnoId: 'alu-01', hora: '19:30', sesion: 'Base volumen' },
  ],
  alertasBienestar: [
    {
      alumnoId: 'alu-05',
      detalle: 'Fatiga 1/5 y sueño 2/5 en 2 sesiones (1=peor / 5=mejor)',
    },
    {
      alumnoId: 'alu-03',
      detalle: 'Estrés 2/5 en última sesión (1=peor / 5=mejor)',
    },
  ],
  alertasDolor: [
    {
      alumnoId: 'alu-05',
      detalle: 'Dolor alto reportado en hombro derecho',
      zona: 'Hombro derecho',
      nivel: 'alto',
    },
  ],
  adherenciaSemanal: 84,
  rpePromedio: 7.4,
  proximosTest: [
    { alumnoId: 'alu-04', fecha: '2026-11-08', tipo: 'Simulacro total' },
    { alumnoId: 'alu-06', fecha: '2026-11-10', tipo: 'Test 1RM sentadilla' },
  ],
};

export const SEGUIMIENTO_SEED = {
  tonelajeBasicosDia: 12480,
  tonelajeSemanal: 61200,
  volumenPorLevantamiento: [
    { nombre: 'Sentadilla', sets: 28 },
    { nombre: 'Press banca', sets: 26 },
    { nombre: 'Peso muerto', sets: 18 },
  ],
  intensidadMedia: 74,
  rpeObjetivo: 7.5,
  rpeReal: 8.1,
  cumplimiento: 88,
  adherencia: 84,
  oneRmEstimado: [
    { semana: 'S1', squat: 205, bench: 140, deadlift: 245 },
    { semana: 'S2', squat: 208, bench: 142, deadlift: 248 },
    { semana: 'S3', squat: 210, bench: 144, deadlift: 250 },
    { semana: 'S4', squat: 212, bench: 145, deadlift: 252 },
  ],
  bienestarSemanal: [
    { semana: 'S1', promedio: 3.8 },
    { semana: 'S2', promedio: 3.5 },
    { semana: 'S3', promedio: 3.2 },
    { semana: 'S4', promedio: 3.6 },
  ],
  historialDolor: [
    { fecha: '2026-09-18', alumnoId: 'alu-05', nivel: 'alto', zona: 'Hombro derecho' },
    { fecha: '2026-09-20', alumnoId: 'alu-03', nivel: 'leve', zona: 'Lumbar' },
    { fecha: '2026-09-21', alumnoId: 'alu-01', nivel: 'leve', zona: 'Rodilla izquierda' },
  ],
  seriesGrafica: {
    volumen: [42, 48, 55, 52],
    intensidad: [68, 72, 76, 74],
    rpe: [7.1, 7.4, 7.8, 7.4],
    adherencia: [90, 86, 80, 84],
  },
};

export const SUGERENCIAS_IA_SEED = [
  {
    id: 'sug-1',
    titulo: 'RPE superior al objetivo',
    detalle:
      'Andrés Morales reportó RPE 9 en Competition Squat con objetivo 7.5.',
    evidencia: 'Registro sesión 2026-09-22 · RPE real 9 vs objetivo 7.5',
    tipo: 'rpe',
    estado: 'pendiente',
  },
  {
    id: 'sug-2',
    titulo: 'Porcentaje prescrito no logrado',
    detalle:
      'Francisca Negrete logró parcialmente el 80% en press banca (2/4 series).',
    evidencia: 'Cumplimiento parcial · sesión 2026-09-21',
    tipo: 'cumplimiento',
    estado: 'pendiente',
  },
  {
    id: 'sug-3',
    titulo: 'Bienestar bajo en dos sesiones',
    detalle:
      'Francisca Negrete acumula fatiga baja (1–2/5) y sueño bajo en dos sesiones seguidas.',
    evidencia: 'Wellness 2026-09-20 y 2026-09-22 · fatiga ≤2 (1=peor / 5=mejor)',
    tipo: 'bienestar',
    estado: 'pendiente',
  },
  {
    id: 'sug-4',
    titulo: 'Revisar volumen de la próxima sesión',
    detalle:
      'Conviene revisar el volumen de accesorios de Camila Torres ante RPE de sesión 9.',
    evidencia: 'Tonelaje accesorios +18% vs semana previa',
    tipo: 'volumen',
    estado: 'pendiente',
  },
  {
    id: 'sug-5',
    titulo: 'Caída de adherencia',
    detalle:
      'Valentina Ruiz bajó de 90% a 78% de adherencia en 3 semanas.',
    evidencia: '3 sesiones no completadas en las últimas 4 semanas',
    tipo: 'adherencia',
    estado: 'pendiente',
  },
];

export function estadoInicial() {
  return {
    version: STATE_VERSION,
    coach: { ...COACH },
    grupos: GRUPOS.map((g) => ({ ...g })),
    alumnos: ALUMNOS_SEED.map((a) => ({ ...a })),
    ejercicios: EJERCICIOS_SISTEMA.map((e) => ({ ...e })),
    macro: structuredClone(MACRO_SEED),
    micro: structuredClone(MICRO_SEED),
    sesion: sesionSeed(),
    panel: structuredClone(PANEL_SEED),
    seguimiento: structuredClone(SEGUIMIENTO_SEED),
    sugerencias: SUGERENCIAS_IA_SEED.map((s) => ({ ...s })),
    wellness: null,
    registroSesion: null,
    finanzas: finanzasInicial(),
    ui: {
      vista: 'inicio',
      alumnoId: null,
      cargoId: null,
      mesoId: 'meso-2',
      filtroBanco: { texto: '', tipo: '', fuente: '' },
      filtroFinanzas: {
        estado: '',
        grupoId: '',
        modalidad: '',
        coachId: '',
        texto: '',
      },
      ejercicioEditId: null,
      modoAlumno: false,
      mensajeFinanzas: null,
    },
  };
}

/**
 * Migración explícita v1 → v2: preserva planificación, alumnos, wellness,
 * ejercicios y registros; agrega bloque finanzas sin borrar datos deportivos.
 */
export function migrarEstadoV1aV2(v1) {
  if (!v1 || typeof v1 !== 'object') {
    throw new Error('estado_v1_invalido');
  }
  const base = estadoInicial();
  return {
    ...base,
    version: STATE_VERSION,
    coach: { ...base.coach, ...(v1.coach || {}) },
    grupos: Array.isArray(v1.grupos) ? v1.grupos.map((g) => ({ ...g })) : base.grupos,
    alumnos: Array.isArray(v1.alumnos) ? v1.alumnos.map((a) => ({ ...a })) : base.alumnos,
    ejercicios: Array.isArray(v1.ejercicios)
      ? v1.ejercicios.map((e) => ({ ...e }))
      : base.ejercicios,
    macro: v1.macro ? structuredClone(v1.macro) : base.macro,
    micro: v1.micro ? structuredClone(v1.micro) : base.micro,
    sesion: v1.sesion ? structuredClone(v1.sesion) : base.sesion,
    panel: v1.panel ? structuredClone(v1.panel) : base.panel,
    seguimiento: v1.seguimiento
      ? structuredClone(v1.seguimiento)
      : base.seguimiento,
    sugerencias: Array.isArray(v1.sugerencias)
      ? v1.sugerencias.map((s) => ({ ...s }))
      : base.sugerencias,
    wellness: v1.wellness ? structuredClone(v1.wellness) : null,
    registroSesion: v1.registroSesion
      ? structuredClone(v1.registroSesion)
      : null,
    finanzas: finanzasInicial(),
    ui: {
      ...base.ui,
      ...(v1.ui || {}),
      filtroFinanzas: {
        ...base.ui.filtroFinanzas,
        ...((v1.ui && v1.ui.filtroFinanzas) || {}),
      },
    },
  };
}
